### ISSUE TITLE
Stopped working in 2025.6.0b3

### ISSUE THREAD

**Issue by smarthomejunkie** [knudsvik/EnergyScore#117]
Nothing much to say really. The integration stopped working in HA 2025.6.0b3. 

Maybe it’s an issue in the beta, but might be something that has to be changed in the integration. 

Log:

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 11:34:57 AM (6 occurrences)
Last logged: 11:44:14 AM

Error setting up entry Total Energy Score for energyscore
Error setting up entry Test Energy Score for energyscore
Error setting up entry Office Energy Score for energyscore
Error setting up entry Total Netto Energy Score for energyscore
Error setting up entry Test Score Zonneplan electricity consumption today for energyscore
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energyscore/__init__.py", line 32, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by smarthomejunkie** [comment]
It was not the beta. It’s also not working in 2025.6.0. 

Geval message is “Failed to set up”.

**Comment by knudsvik** [comment]
Yes, I think I know why. Just haven't really done any development on this component for the last year. Are you still using it, does it create value?

**Comment by smarthomejunkie** [comment]
I use it on a daily basis. Mainly for cost calculation.

**Comment by MrOzzOnline** [comment]
I'm using it too. It's a neat tool.

**Comment by JuMaPa** [comment]
Also using this integration…was using😩
Hope that can fixit up and running.

**Comment by 02curls** [comment]
I'm using it too daily 😢

**Comment by knudsvik** [comment]
I am taking a look at it. The code has not been updated in ages, so will take a bit time to get up and running again ;)

**Comment by knudsvik** [comment]
This should now be resolved with release 1.3.4. Given you like the integration I may do some more development, have some ideas for improvements :)

**Comment by smarthomejunkie** [comment]
Thank you. It works again! Very nice!

**Comment by AseKarlsson** [comment]
Thanks @knudsvik !
