### ISSUE TITLE
Integration no longer working in Home Assistant 2023.2.0b1

### ISSUE THREAD

**Issue by smarthomejunkie** [knudsvik/EnergyScore#81]
## Version of the custom_component
v1.03

## Describe the bug
After installing the 2023.2.0b1 version the integration is no longer loading.

The log entry is:

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 5:34:16 PM (2 occurrences)
Last logged: 5:43:07 PM

Unable to prepare setup for platform energyscore.sensor: Platform not found (cannot import name 'Optional' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)).

**Comment by smarthomejunkie** [comment]
Thanks. During the creator network meeting yesterday the HA team told something about changes in the helpers. Maybe it's related to that.

**Comment by knudsvik** [comment]
Thanks, is this a recorded event?

**Comment by smarthomejunkie** [comment]
I do not think so. It's a creator's meeting only and shows what's new in the next release so that we can prepare videos.

**Comment by knudsvik** [comment]
@smarthomejunkie The bug has been identified and fixed. Expect a release later today with this fix and a few more improvements. By the way, like your videos and see EnergyScore on your dashboards 👍 In this repository there is a file called [visualisation.md](https://github.com/knudsvik/EnergyScore/blob/master/visualisation.md) which shows an alternative way of presenting the energyscore using apexchart.

**Comment by knudsvik** [comment]
v1.1.0 was just released. Should be available in HACS within the hour.

**Comment by smarthomejunkie** [comment]
Great,
Thank you. I will create a video about your integration shortly. 😉

**Comment by smarthomejunkie** [comment]
The score stays 100% since this update. There are also no attributes in the site entity. Should I recreate it?

state_class: measurement
energy_entity: sensor.zonneplan_p1_electricity_consumption_today
price_entity: sensor.zonneplan_current_electricity_tariff
quality: 0
total_energy:
  2023-01-28T19:00:00+0100: 11.66
price:
  2023-01-28T19:00:00+0100: 0.34
last_updated: '2023-01-28T19:37:26.618590+01:00'
unit_of_measurement: '%'
icon: mdi:speedometer
friendly_name: Total Energy Score

**Comment by knudsvik** [comment]
> The score stays 100% since this update. There are also no attributes in the score entity. Should I recreate it?
> 
> 
> 
> state_class: measurement
> 
> energy_entity: sensor.zonneplan_p1_electricity_consumption_today
> 
> price_entity: sensor.zonneplan_current_electricity_tariff
> 
> quality: 0
> 
> total_energy:
> 
>   2023-01-28T19:00:00+0100: 11.66
> 
> price:
> 
>   2023-01-28T19:00:00+0100: 0.34
> 
> last_updated: '2023-01-28T19:37:26.618590+01:00'
> 
> unit_of_measurement: '%'
> 
> icon: mdi:speedometer
> 
> friendly_name: Total Energy Score
> 
> 

Oh no, fixing one thing and a new one arrises :) I am pretty sure what the issue is, can probably fix this tonight!

**Comment by smarthomejunkie** [comment]
Ah okay. I saw that the energy dashboard is also not working anymore, so might be beta related as well.

**Comment by knudsvik** [comment]
Thanks for reporting @smarthomejunkie . It is not related to the energy dashboard, it was just a sloppy implementation of the new energy treshold feature on my end. Version 1.1.2 has this fixed and should be available in HACS real soon.

**Comment by smarthomejunkie** [comment]
Thank you again for your swift response!

**Comment by knudsvik** [comment]
well.. don't thank me yet. v1.1.2 seems to bring new problems to my home assistant instance at least.. working on it.

**Comment by knudsvik** [comment]
v1.1.3 will have the bug fixed.
